### ISSUE TITLE
404 when root directory is file system root

### ISSUE THREAD

**Issue by thorstenkampe** [aperezdc/ngx-fancyindex#107]
I get a 404 for `https://localhost` when nginx' root directory is the file system root (`root /;`). `https://locatlhost/etc` works. Substituting `fancyindex` with `autoindex` resolves the issue.

**Comment by ryandesign** [comment]
Confirmed.

nginx autoindex fixed this bug in 2007: https://github.com/nginx/nginx/commit/4c89c09ad8e574509446efab0347b124372bc53a

I submitted a PR to backport this.
