### ISSUE TITLE
Still not in package management

### ISSUE THREAD

**Issue by jult** [aperezdc/ngx-fancyindex#109]
Installing nginx-full or nginx-extras in debian does not provide me with the fancyindex module.

Can someone point me to a non-source repo install method that actually works for debian 9 ?
I get nginx 1.10.* everytime I try and install this module, and the module isn't there.

And yes, I did try

apt remove nginx nginx-extras nginx-common nginx-full -y --allow-change-held-packages

but as soon as I try either nginx-full or nginx-extras, it will not provide me with anything other than NGINX 1.10.*

**Comment by alehaa** [comment]
`nginx-extras` has a dependency to the fancyindex package set, even in stretch for NGINX 1.10.*. Installing this package and using fancyindex should work out of the box.

**Comment by jult** [comment]
Except I need a newer version of nginx than 1.10. * (full of unpatched vulnerabilities, for one..) 
Everybody out there recommends using an Nginx stable or mainline repo with apt.
And when I do there's no fancy index module in either Nginx-full of Nginx-extras.

**Comment by alehaa** [comment]
The current stable release of Debian is `buster`, not `stretch`, i.e. Debian 10.

**Comment by jult** [comment]
So? I'm not getting anything higher than 1.10.* when I install using debian alone. https://docs.google.com/spreadsheets/d/1zvCb0xuI1gafUFvtr_RhYS4E8bnlk2sQzwjor4MrXEs/edit#gid=0
