### ISSUE TITLE
HTML5, fixing the html for accessibility, and getting the latest version into nginx-extras?

### ISSUE THREAD

**Issue by digitaltoast** [aperezdc/ngx-fancyindex#12]
Hi; thanks for a great module and I love the look of it but I appear to be "stuck" on an old version; I'm currently using the nginx-extras mainline 1.7.0 from the standard Ubuntu 14.04 repo, and I noticed the page gives a bunch of validation errors.

But I also noticed that the headers from my nginx look like

``` html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head><meta http-equiv="content-type" content="text/html; charset=utf-8"/>
```

while the template file on github looks like

```html
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="content-type" content="text/html; charset=utf-8"/>
<meta name="viewport" content="width=device-width"/>
```

This suggests that even though this template is 5 months old, it's not making into nginx-extras builds from 2 weeks ago. Who should I prod or nudge for this?

I'd also like to make the page more accessible, eg for screenreader users, by adding some simple [ARIA](http://en.wikipedia.org/wiki/WAI-ARIA) tags and semantics, which wouldn't affect the actual structure or markup. If I were to tweak about and make some changes which didn't affect current templates but made it valid html5 and WAI-compliant, would it be worth submitting a pull request?

Footnotes: I realise, of course, I could just "fudge" the whole thing by dropping some jquery into the footer which would modify the elements in question, but you'd be surprised how many screenreader users have javascript off, so that's a less preferable route.

And I also realise that I *could* modify the ngx-fancyindex source and compile into nginx, but that way lies a ridiculous amount of time and security issues when you're relying on as many extras as nginx-extras provides... being able to "apt-get update" everything is so much safer.

**Comment by aperezdc** [comment]
@digitaltoast: Ping. Please see the previous comment... may I close this issue?

**Comment by digitaltoast** [comment]
Oh, yes, sorry. And yes, please do. Life took an odd turn which distracted me from other things for a while, just catching up now :)
