### ISSUE TITLE
Add an option for setting the default sort

### ISSUE THREAD

**Issue by fletchowns** [aperezdc/ngx-fancyindex#14]
It would be awesome if there was directive to control the default sort, something like:

```
fancyindex_default_sort [name | size | date]
```

**Comment by archshift** [comment]
Any progress on this?

**Comment by Jamim** [comment]
I implemented this option. Check it, please.
Jamim/ngx-fancyindex@f1537deb2dfc41663d199b59ba42636db2cd93af

**Comment by aperezdc** [comment]
@Jamim: Thanks a lot for implementing the option, I have merged your commit :+1:
