### ISSUE TITLE
License ambiguity

### ISSUE THREAD

**Issue by ryandesign** [aperezdc/ngx-fancyindex#149]
The LICENSE file in this repository is the 2-clause BSD license, which is the same as nginx's. However t/preamble says it is "Distributed under terms of the MIT license". Is this just an oversight—should t/preamble be changed to be under the BSD license like the rest of the project?

**Comment by aperezdc** [comment]
@ryandesign Definitely an oversight, thanks for spotting this. As it happens, I have editor templates for new files and by default the shell script template mentions the MIT license.
