### ISSUE TITLE
Missing Saturday in the long_weekday array

### ISSUE THREAD

**Issue by 10geek** [aperezdc/ngx-fancyindex#157]
I found a small but significant bug: the long_weekday array is missing a Saturday.
https://github.com/aperezdc/ngx-fancyindex/blob/f50d7b799f56ba722732f0e7d70da57b455d8aa8/ngx_http_fancyindex_module.c#L40

**Comment by aperezdc** [comment]
Fixed, thanks for noticing this issue @10geek &mdash; it's amazing that it went for so long unnoticed 🤯
