### ISSUE TITLE
Incorrect line endings in template.h after template.html processing

### ISSUE THREAD

**Issue by Jamim** [aperezdc/ngx-fancyindex#19]
Fix is here: @c1a9bd970125c1c215981d03492cda479c967578

**Comment by aperezdc** [comment]
Thanks! Like in the case of pull request #20, this is implemented that way on purpose, to make the generated HTML smaller and save bandwidth. If there is some other reason why this should be included, I will be happy to know.

**Comment by Jamim** [comment]
Sorry, the is no other reason.

**Comment by aperezdc** [comment]
Then I would rather not merge this. If someone wants a well indented version of the generated content, there's always the option of using the "tidy" command on it.
