### ISSUE TITLE
Option for not limiting maximum length of file names

### ISSUE THREAD

**Issue by aperezdc** [aperezdc/ngx-fancyindex#2]
Currently the length of file names in directory listings generated by the module are limited to 50 characters:

```c
#define NGX_HTTP_FANCYINDEX_NAME_LEN  50
```

Instead of placing an ellipsis character in the output for long file names, it would be interesting to be able to set the maximum length with a directive in the configuration file. One of the options could be allowing any length (thus never trimming the names).

**Comment by Jamim** [comment]
This feature is already implemented by @lachs0r: @8f755a6588a59d4ad1526b238bd5ac1ae8046e86

**Comment by aperezdc** [comment]
This is now merged in `master`.

@lachs0r: Thanks a lot for the patch!
@Jamim: and thanks for pointing out the commit.
