### ISSUE TITLE
Support for processing tabs in template.html

### ISSUE THREAD

**Issue by Jamim** [aperezdc/ngx-fancyindex#20]
Implemented here: @d9dfa328f0d785046b1c0c4ec792bd2b66557465

**Comment by aperezdc** [comment]
First of all, thanks for submitting your patch as a pull request. If I understand correctly the idea here is that the HTML generated by the FancyIndex module would be better indented when sent to the client. Given that browsers do not really care about indentation and how nice the HTML is (as long as it's valid and it can be parsed), this is not really needed.

Moreover, it makes the generated HTML contain more bytes, and the less bytes transferred to clients, the better. Think about it this way: if the generated HTML contains 10 bytes lesss, every 100.000 visits the server is generating 1GB less of bandwidth consumption.

If there some other reason to include this apart from making the HTML look prettier, please let me know. If pretty HTML is the only reason, I would rather not have this change merged.

**Comment by Jamim** [comment]
Sorry, there is no other reason.
But results code looks pretty nice :-)

For example:
Index page of http://ensemplix.mim.pw/images/items/ contains 2707 bytes.
80 bytes (2.96%) of size is a lines endings. Not so much.
At the same time, request+response headers size is about 500 bytes (depends on browser).

Anyway, I think option to force save bandwidth (for remove lines endings, tabs and spaces between tags) would not be superfluous.

**Comment by aperezdc** [comment]
If the reason is only cosmetic, then I would rather not merge this change. Sorry about that. I appreciate your contribution, anyway. Thanks!
