### ISSUE TITLE
Foreign directory listings cause Javascript error

### ISSUE THREAD

**Issue by gflohr** [aperezdc/ngx-fancyindex#21]
You cannot navigate into a directory that is not handled by fancyindex.  The error is caused by history.js:

    var elements = div.getElementsByClassName('box-content')[0];
    target.innerHTML = elements.innerHTML;

The html of "div" is the content of the directory listing.  But this listing may not be generated by fancyindex, so that "elements" is null, and accessing the property innerHTML will trigger an exception.

I fixed that by setting the location and returning false in case "elements" is null.

A somewhat better approach would be to let fancyindex send a custom header and check that header instead of relying on the presence of an element with the class name 'box-content".  And the best fix would be to not fire the ajax request at all if a link points to a location that is not handled by fancyindex.

**Comment by aperezdc** [comment]
@gflohr: There is not JavaScript code being used in the FancyIndex module. Are you using a fork? If so, which one?

**Comment by gflohr** [comment]
Oops, you're right.  The JavaScript file belongs to the theme supplied by @TheInsomniac that I installed some time ago, and forgot then.  Sorry! Please close the bug.

**Comment by aperezdc** [comment]
Thanks for confirming. I will close this issue as invalid. Thanks for your time anyway!
