### ISSUE TITLE
in OSX 10.9+ MD5 deprecated has gone from warning to error and causes Make to stop

### ISSUE THREAD

**Issue by findmory** [aperezdc/ngx-fancyindex#22]
when you run the makefile you will get messages such as:
'MD5_Update' is deprecated: first deprecated in OS X 10.7
      [-Werror,-Wdeprecated-declarations]

To avoid configure with the no-deprecated-declarations flag such as:
 ./configure --add-module=../ngx-fancyindex-master --with-cc-opt="-Wno-deprecated-declarations"

**Comment by aperezdc** [comment]
This is not an issue of the fancy index module itself, which does not use the MD5_Update function itself.
