### ISSUE TITLE
Provide directive to configure time format

### ISSUE THREAD

**Issue by reorx** [aperezdc/ngx-fancyindex#23]
`fancyindex_localtime` can only determine the timezone, but people in different timezones used to print time in different ways (as a Chinese, I would like to see time formatted like `2015-04-16 23:33`), it would be very great to provide directive to configure that. The directive may looks like:

```
location / {
    fancyindex on;
    fancyindex_time_format "yyyy-MM-dd h:mm"
}
```

to represent time as `2015-04-16 23:33`, use [Unicode Date/Time Patterns](http://cldr.unicode.org/translation/date-time-patterns) as [formatting symbol](http://cldr.unicode.org/translation/date-time), which may already have C implementation so that it can be easier to achieve in this project :)

**Comment by aperezdc** [comment]
@reorx: How about using a [strftime](http://linux.die.net/man/3/strftime)-style format expression? I won't be implementing it using `strftime()` directly to avoid passing a string supplied by the user in the configuration file directly to it, but people are already familiar with how it works and I could implement just the most useful of the format specifiers (year, month, day, hour, time, and so on). What do you think?

**Comment by reorx** [comment]
It would be great if you use `strftime`, which I think is better than the unicode patterns I mentioned before! Its widely used in many languages and cli tools. But I am wondering why you want to avoid using `strftime` directly, in my opinion if you decide to implement a feature, it's better to make it fully functional to satisfy user's needs, so that you won't be requested to replenish the feature continuously.

**Comment by aperezdc** [comment]
@reorx: One reason is that whatever is written in the configuration file should be considered untrusted input. If the parameter is passed directly to `strfime()`, one could use a format specifier that is not implemented by the function. In most Unixes that would make the function return zero, but in Windows it can call an “invalid parameter handler”, which has the a default implementation that throws an exception — and Nginx would abort execution because of the unhandled exception. I think it is better to eother provide a safe subset of the formats supported by `strftime()`, or providing a custom syntax.

**Comment by aperezdc** [comment]
@reorx: Also, using `strftime()` directly may yield different results depending on the current locale. That means that, if someone runs Nginx with the `LANG` variable set to different values, the output will change. I would rather have the formatting output be stable regardless of the environment.

I'm gonna go ahead and implement myself a small subset of the `strftime()` format specifiers.

**Comment by aperezdc** [comment]
@reorx: I have pushed the commit that adds the `fancyindex_time_format` configuration directive, and I will wait some days before making a new release. It would be great if you could give it a try before the release, just in case there is something that needs fixing. I am planning on doing the next release in week, approximately.

**Comment by reorx** [comment]
Great job! I will test it later if I get time today or tomorrow, and give a feedback here.
