### ISSUE TITLE
Documentation gap

### ISSUE THREAD

**Issue by igenchev** [aperezdc/ngx-fancyindex#26]
The fancyindex_header and fancyindex_footer functions fail (and log alerts) without the 'ngx_http_addition_module'. This needs to be stated in the requirements, otherwise somebody like me will build a version of nginx that only does errors when trying to use custom header/footer.

**Comment by aperezdc** [comment]
I have updated the README, plus the `config` script for the module will now warn at configuration time when the addition module is not enabled. Do you think it would be good to completely disable building support for the `fancyidex_footer` and `fancyindex_header` directives when the addition module is disabled?

**Comment by igenchev** [comment]
Ultimately your choice, but I would hope a warning at configure time will be enough for everyone.

**Comment by aperezdc** [comment]
@igenchev: Okay, let's go with the warning for now. It is already an improvement, and I expect people who are building Nginx are likely to notice the message when the module is configured.
