### ISSUE TITLE
Minor feature request: config option to exclude symbolic links

### ISSUE THREAD

**Issue by DarkHelmet433** [aperezdc/ngx-fancyindex#27]
I have a couple of cases where there are symbolic links for Reasons(TM) but I'd like crawlers to stop seeing them.

I have a trivial prototype patch:
```
--- ngx_http_fancyindex_module.c.dist	2015-02-19 04:16:36.000000000 -0800
+++ ngx_http_fancyindex_module.c	2015-08-05 14:58:51.965238000 -0700
@@ -494,7 +494,7 @@
 
         len = ngx_de_namelen(&dir);
 
-        if (ngx_de_name(&dir)[0] == '.')
+        if (ngx_de_name(&dir)[0] == '.' || ngx_de_is_link(&dir))
             continue;
 
 #if NGX_PCRE
```
This will do for us, but was thinking it might be nice to have it in the upstream version with a configuration control.

I know nginx itself has an option whether or not to follow symlinks, but that is exactly the opposite of what we want. If it is blocked there, fancyindex will generate href links that result in a 404.

**Comment by aperezdc** [comment]
This seems like an interesting feature to have, I can think of a couple of uses myself  :+1: 
I'll be adding a configuration flag for this.

**Comment by aperezdc** [comment]
@DarkHelmet433: I have pushed a commit that implements filtering of symbolic links as suggested, and that can be toggled using a configuration directive. It works for me, but I am still going to wait a little while before making the next release, so feel free to check it out the feature building from Git and comment in case the feature does not work for you. Ah, and thanks again for the suggestion :bulb:

**Comment by DarkHelmet433** [comment]
I checked it out from git, but it segfaults while parsing.  One of the followup commits created a null pointer dereference.  I've attached a fix as a pull request.  #28 I believe.

And again, thanks for taking the time to work on this!
