### ISSUE TITLE
Lump folder and file modification dates together?

### ISSUE THREAD

**Issue by SEIKT** [aperezdc/ngx-fancyindex#36]
Is it possible to combine the sorting of the modification dates of files and folders? Currently, the modification dates of files and folders are grouped separately.

**Comment by aperezdc** [comment]
@SEIKT: It is not possible. The current sorting methods always prioritize folders first. It wouldn't be difficult to make the sorting ignore folders and apply the sorting globally to all the entries. Are you interested in an option for that? Is it enough that it is a configuration option, or would it need to be selectable with a query parameter in the URL?

**Comment by SEIKT** [comment]
Hey man. Thanks for the quick response. What you suggested sounds great. I wouldn't mind either option, whichever one is easier for you to implement.

**Comment by aperezdc** [comment]
@SEIKT: A config file option is certainly easier to implement. Let's go with that solution first, and if needed the query string parameter can be added later on.

**Comment by SEIKT** [comment]
Champion. Thank you. Look forward to it.

**Comment by aperezdc** [comment]
@SEIKT: This feature has not landed in the repository, there is now a `fancyindex_directories_first` directive, see #40 for details.
