### ISSUE TITLE
Randomize execution order of tests

### ISSUE THREAD

**Issue by aperezdc** [aperezdc/ngx-fancyindex#49]
Ideally tests (`t/*.test`) should be self-contained, and the order of their execution wouldn't matter. To further ensure that, it would be desirable to modify the test harness to execute them in a random order.

**Comment by fadc80** [comment]
It sounds good, but I think this is not going to ensure your tests will always fail when they depend on each other.

**Comment by aperezdc** [comment]
@fadc80: Precisely the idea is that each unit test should be, er... a single *unit*, independent from the rest. Having them run in a random order makes sure that nobody will introduce later on tests which are not self-contained.

The PR was just what is needed, so I merged it already. Thanks for your contribution!
