### ISSUE TITLE
Allow decimal digits in rounded file sizes

### ISSUE THREAD

**Issue by aperezdc** [aperezdc/ngx-fancyindex#51]
When file sizes are being rounded (`fancyindex_exact_size` is disabled), it's not very useful to report a 4.9 GiB file as `4G`: it would actually be good to include a decimal digit and show the value as `4.9G`. This is specially true for magnitudes of MiB and bigger.

**Comment by aperezdc** [comment]
The main complication for implementing this is that the rounding is done using integer arithmetic, and also that sizes in bytes should *never* have decimal digits.

**Comment by AndersTrier** [comment]
Implemented in #53

**Comment by aperezdc** [comment]
Milestone added. I think it should be possible to get this merged for the next point release.

**Comment by aperezdc** [comment]
Closing, the PR has been merged for a while in `master`.
