### ISSUE TITLE
hidden files

### ISSUE THREAD

**Issue by pmaster555** [aperezdc/ngx-fancyindex#54]
how to enable display of the files (or folders) that begin with a dot?

**Comment by aperezdc** [comment]
Currently files which start with a dot are always ignored by the module, and never show in the generated file listings. In Unix systems the convention is that those files are hidden, is there any reason why would you want to unhide them?

One option could be to add a boolean configuration directive to show all the files, for example `fancyindex_show_hidden_dot_files`. Would something like that work for you?

**Comment by pmaster555** [comment]
fancyindex I use to access all the players to the screenshots of the game call of duty 4. but the screenshots are stored at ../.callofduty4/screeshots
use option fancyindex_show_hidden_dot_files would solve the problem. I do not think it is useful to me alone

**Comment by aperezdc** [comment]
@pmaster555 I guess you are serving an index generated for the directory which contains the `.callofduty4/` subdirectory, so an `alias` won't do... well I don't see another way around, so implementing the option to show the hidden files will be needed in the end.

**Comment by machacke** [comment]
use command ls -a to show hidden files in directory

**Comment by pmaster555** [comment]
Ls -a ? in nginx?

**Comment by aperezdc** [comment]
@pmaster555: By the way, you could do something like this in your `nginx.conf`:

```nginx
location /callofduty/screenshots {
   root /path/to/.callofduty4/screenshots;
}
```

This does not need any change in the Fancyindex module.

**Comment by aperezdc** [comment]
@pmaster555: Have you tried the suggested approach of using a `location` directive? Did it work for you?
