### ISSUE TITLE
hide Parent directory  ..

### ISSUE THREAD

**Issue by nico8948** [aperezdc/ngx-fancyindex#57]
Hide the parent directory (..):
fancyindex_ignore ..;

fancyindex_ignore ..  will hide all accept parent dir.

**Comment by aperezdc** [comment]
The parent directory entry (`..`) is hardcoded in [template.html](https://github.com/aperezdc/ngx-fancyindex/blob/master/template.html#L67). One option would be to provide your own modified version of it when building the module. This will work to hide the `..` entry for _all the directory listings_. Or do you want to hide it only for certain locations?

**Comment by aperezdc** [comment]
@nico8948: Ping. Could you comment on this?

**Comment by aperezdc** [comment]
This has been implemented by @kPherox in #99 (thanks!)
