### ISSUE TITLE
How to render <title> when using custom header?

### ISSUE THREAD

**Issue by Daniel15** [aperezdc/ngx-fancyindex#58]
When I'm using a custom header, how do I render the right `<title>` tag? The default template renders something like`<title>Index of /test/</title>`. Is there a placeholder/variable I can include in my custom header?

**Comment by Daniel15** [comment]
Never mind, I guess I can just make the header a PHP script and use `$_SERVER['REQUEST_URI']`

**Comment by aperezdc** [comment]
@Daniel15: Yes, a custom header is the easiest way, as you have found out already. Good to know that it's working for you :+1:
