### ISSUE TITLE
Unknown directive fancyindex

### ISSUE THREAD

**Issue by revolter** [aperezdc/ngx-fancyindex#64]
I followed all the steps in the README but upon running `sudo nginx -t` it prints this:

> nginx: [emerg] unknown directive "fancyindex" in /usr/local/etc/nginx/nginx.conf:51
nginx: configuration file /usr/local/etc/nginx/nginx.conf test failed

I installed `nginx` with the command:

    PREFIX=/usr/local
    ETCDIR=${PREFIX}/etc/nginx
    ./configure \
        --prefix=${ETCDIR} \
        --with-cc-opt="-I ${PREFIX}/include" \
        --with-ld-opt="-L ${PREFIX}/lib" \
        --conf-path=${ETCDIR}/nginx.conf \
        --sbin-path=${PREFIX}/sbin/nginx \
        --pid-path=/var/run/nginx.pid \
        --error-log-path=/var/log/nginx-error.log \
        --user=www --group=www \
        --without-http_rewrite_module \
        --add-dynamic-module=/home/revolt/downloads/ngx-fancyindex-0.4.1

`nginx.conf` constains:

    location /test {
        root html;
        fancyindex on;
    }

`$ sudo nginx -V`:

> nginx version: nginx/1.11.8
built by clang 3.4.1 (tags/RELEASE_34/dot1-final 208032) 20140512
configure arguments: --prefix=/usr/local/etc/nginx --with-cc-opt='-I /usr/local/include' --with-ld-opt='-L /usr/local/lib' --conf-path=/usr/local/etc/nginx/nginx.conf --sbin-path=/usr/local/sbin/nginx --pid-path=/var/run/nginx.pid --error-log-path=/var/log/nginx-error.log --user=www --group=www --without-http_rewrite_module --add-dynamic-module=/home/revolt/downloads/ngx-fancyindex-0.4.1

`$ uname -a`:

> FreeBSD revolt 10.3-RELEASE FreeBSD 10.3-RELEASE #0 r297264: Fri Mar 25 02:10:02 UTC 2016     root@releng1.nyi.freebsd.org:/usr/obj/usr/src/sys/GENERIC  amd64

**Comment by revolter** [comment]
Apparently, you need to load the module too using `load_module "modules/ngx_http_fancyindex_module.so";`.

**Comment by aperezdc** [comment]
@revolter: Good catch, this is indeed missing in the documentation. Let's check that PR...

**Comment by aperezdc** [comment]
PR merged, thanks @revolter!
