### ISSUE TITLE
[Question] how to reverse sort?

### ISSUE THREAD

**Issue by Benman2785** [aperezdc/ngx-fancyindex#77]
hi,

i run nginx 1.12.1 (latest stable) + nginx-rtmp-module + your ngx-fancyindex

how can i reverse the sort - e.g. i want to have biggest file on top and not smallest file - how do i do that?

**Comment by Benman2785** [comment]
still needed

**Comment by aperezdc** [comment]
@Benman2785: Sorry that I didn't reply to this before, please accept my apologies.

Once a directory listing is loaded by your Web browser, you can click on the arrows in the table headings to change the sorting criteria and direction.

**Comment by Benman2785** [comment]
http://benmanshafen.de/vids/github/ngx-fancyindex/ngx-fancyindex_sort-error-filesize.mp4

as i said it didnt work ;)

but i have to check my version first - maybe i dont use v0.4.2

**Comment by Benman2785** [comment]
http://benmanshafen.de/vids/github/ngx-fancyindex/ngx-fancyindex_sort-error-filesize.jpg

nope - i use v0.4.2
