### ISSUE TITLE
Support case-insensitive sorting by file names

### ISSUE THREAD

**Issue by glomie** [aperezdc/ngx-fancyindex#78]
According to ascii order, the lowercase letter is bigger than the uppercase letter. For example, it shows "Afilename,Bfilename" and then "afilename". It's not suitable for me to find the file. So can you list the files  ordering by ignore-case filename?

**Comment by aperezdc** [comment]
@glomie: I understand that this is a feature request to support case-insensitive sorting, so am editing the issue title to make it a bit clearer. Please comment if that is not the case.

There's also issue #60 about improving sorting methods, so I will try to solve both issues together for [version 0.5.0](https://github.com/aperezdc/ngx-fancyindex/milestone/5).

Thanks for your suggestion!

**Comment by glomie** [comment]
@aperezdc Thanks very much.Your answer is appropriate and polite.

**Comment by FredericaBernkastel** [comment]
That's too slow.
I'll make it myself.

**Comment by ryandesign** [comment]
This has been implemented in #124.
