### ISSUE TITLE
Wrong trimming of utf-8 filenames

### ISSUE THREAD

**Issue by hempalex** [aperezdc/ngx-fancyindex#80]
If filename is longer than fancyindex_name_length and contains non-latin symbols it would be trimmed in wrong way, in bytes not utf-8 codepoints.

Maybe it should respect charset settings?

**Comment by aperezdc** [comment]
Yes, that is a bit unfortunate and the current implementation is overly naïve. While invalid UTF-8 sequences won't break any browser, it does make them show replacement characters (more information [in this article](https://hsivonen.fi/broken-utf-8/)).

One option may be to chop off the string at the maximum configured length, and if that point falls in the middle of a multibyte UTF-8 sequence, go back to the latest valid one and trim the bytes from the malformed sequence.

**Comment by weakestan** [comment]
It's js unescape bug
in footer.html  replace window.unescape to  decodeURIComponent
u can fix it.

**Comment by baoang** [comment]
same problem, but an easy workaround is to increase the max length, say, from 50 to 100, so that the long title could be displayed.

**Comment by ryandesign** [comment]
I suppose this can be closed now that `fancyindex_name_length` has been removed and no truncation of the file name happens anymore.

**Comment by aperezdc** [comment]
> I suppose this can be closed now that `fancyindex_name_length` has been removed and no truncation of the file name happens anymore.

Indeed, thanks for noticing!
