### ISSUE TITLE
New fancyIndex Theme

### ISSUE THREAD

**Issue by fraoustin** [aperezdc/ngx-fancyindex#87]
Hi,
I created a new fancyindex theme (https://github.com/fraoustin/Nginx-Fancyindex-Theme)
It use the framework mdl (Material Design Lite https://getmdl.io/) it works with screen or mobile.

Can you add in your README my theme?
Thank you

**Comment by alehaa** [comment]
I've also created [a flat theme, based on bootstrap 4](https://github.com/alehaa/nginx-fancyindex-flat-theme). Would be nice, if that could be added, too. ;)

**Comment by aperezdc** [comment]
Both themes added to the README, thanks for the suggestions!

**Comment by alehaa** [comment]
Thanks! ;)
