### ISSUE TITLE
Please Add the support of Nginx 1.14.x feature

### ISSUE THREAD

**Issue by kongfanhe303690396** [aperezdc/ngx-fancyindex#89]
Please Add the support of Nginx 1.14.x feature

**Comment by aperezdc** [comment]
@kongfanhe303690396 I have just built the module successfully with Nginx 1.14.0 and it seems to work fine. Did you run into any trouble? Is there some that does not work for you?

**Comment by davidjb** [comment]
Ditto to not seeing no issues with building for 1.14.0; tested and working fine for my nginx installs.

**Comment by aperezdc** [comment]
@davidjb Thanks for confirming that the module also works for you with Nginx 1.14

@kongfanhe303690396 I will be closing this issue for now, but if you still experience issues with Nginx 1.14, please reopen the issue and provide some information about your setup (Nginx compilation options, platform, operating system, etc). A build log would be most useful.
